---
name: sample
### Recibe una lista de ficheros con sus nombres y realiza una pull request con ellos sobre main
on:
  workflow_dispatch:
    inputs:
      folder_path:
        description: 'Folder to create if not exists'
        required: true
        default: ''

env:
  WORKFLOW_VERSION: 1.0.0 
  SCM_EMAIL: javiAlc@github.com
  SCM_USERNAME: javiAlc
  BRANCH_NAME: ''
  FOLDER_CREATED: false

jobs:
  Sample:
    name: Sample
    timeout-minutes: 5
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0          
          ref: main
          repository: JaviAlc/worflow-testing
      - name: Prepare committer information
        run: |
          git config user.name "${{env.SCM_USERNAME}}"
          git config user.email "${{ENV.SCM_EMAIL}}"
      - name: Get actual branch for Pull Request
        run: |
          BRANCH_NAME=$(echo $GITHUB_REF | sed 's/refs\/heads\///')
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV
          echo actual: "${{env.BRANCH_NAME}}"
      - name: Show actual branch name
        run: |
          echo "${{env.BRANCH_NAME}}"
      - name: Check if folder exists and create if not
        run: |
          if [ ! -d ${{ inputs.folder_path }} ]; then
            mkdir -p ${{ inputs.folder_path }}
            echo "FOLDER_CREATED=true" >> $GITHUB_ENV
            echo "Folder created"
          fi
      - name: Create a file in folder
        run: |
          if [ ${{env.FOLDER_CREATED}} = true ]; then
            echo "Folder created"
            touch ${{ inputs.folder_path }}/test.txt
          else
            echo "Folder already exists"
            echo "test" > "${{ inputs.folder_path }}/$test2.txt"
          fi
      - name: Print folders
        run: |
          ls -la ${{ inputs.folder_path }}
        
          
        